name: Label High Risk PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-high-risk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if configuration.prod.yml is modified
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            config-prod:
              - 'configuration.prod.yml'

      - name: Add 'High risk' label
        if: steps.filter.outputs.config-prod == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: High risk

      - name: Post warning comment and tag reviewer team
        if: steps.filter.outputs.config-prod == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            const commentBody = `⚠️ **High Risk Change Detected**

This pull request includes changes to \`configuration.prod.yml\`, which may impact production configuration.

@your-org/api-reviewers — please review this PR carefully before approving.`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: commentBody
            });
